language: python
python:
  - "2.7"
services: mysql

env:
  - DJANGO_VERSION=1.7

# command to install dependencies
install:
  - pip install Django==$DJANGO_VERSION
  - pip install mysql-python
  - pip install elasticsearch
  - pip install Pillow

# command to run test
before_script:
  - mysql -e 'CREATE DATABASE biodesigner'
  - python manage.py syncdb --noinput

script: python manage.py test